dist:       trusty
sudo:       required
language:   cpp
install:    make get-deps
script:     mkdir build && cd build && cmake .. && make test

addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-5.0
        - george-edison55-precise-backports
    packages:
        - cmake-data
        - cmake
        - clang-5.0
        - g++-7

matrix:
    include:
        - os: linux
        env:
            - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"
